from ._reflModel import ReflectometryModel

from ._sphereCSStacked import SphereCSStacked
from ._sphereCSStackedSpacer import SphereCSStackedSpacer
from ._sphereCSStackedLinearSpacer import SphereCSStackedLinearSpacer
from ._sphereCSStackedParabolicSpacer import SphereCSStackedParabolicSpacer
from ._sphereCSStacked5 import SphereCSStacked5
from ._sphereCSStacked5Spacer import SphereCSStacked5Spacer
from ._sphereCSStacked6 import SphereCSStacked6
from ._sphereCSStacked6Spacer import SphereCSStacked6Spacer
from ._sphereCSStacked11Spacer import SphereCSStacked11Spacer
from ._cmplx_sphereCSStacked import CmplxSphereCSStacked
from ._cmplx_sphereCSStacked11Spacer import CmplxSphereCSStacked11Spacer

from ._sphereCSSStacked import SphereCSSStacked
from ._sphereCSSStacked6Spacer import SphereCSSStacked6Spacer
from ._cmplx_sphereCSSStacked import CmplxSphereCSSStacked
from ._cmplx_sphereCSSStacked6Spacer import CmplxSphereCSSStacked6Spacer

from ._cubeCSStacked import CubeCSStacked
from ._cubeCSDoubleLayer import CubeCSDoubleLayer
from ._oneLayer import OneLayer
from ._substrate import Substrate
from ._cubeCSMonolayer import CubeCSMonolayer
from ._cubeCSMonolayerOnSpacer import CubeCSMonolayerOnSpacer


from ._cmplx_cubeCSDoublelayerOnSpacer import CmplxCubeCSDoublelayerOnSpacer
from ._cmplx_cubeCSDoublelayerOnSpacerNoPMMA import CmplxCubeCSDoublelayerOnSpacerNoPmma
from ._cmplx_cubeCSMonolayerOnSpacer import CmplxCubeCSMonolayerOnSpacer

# decorating functions
from ._instrumentalResolution import InstrumentalResolution
from ._dataResolution import DataResolution
from ._magnetic import Magnetic
from ._magneticSF import MagneticSF
from ._shiftQ import ShiftQ